version: "3"
services:
  react-chatbot:
    image: mjrdockerregistry.azurecr.io/react-chatbot-web:v1
    ports:
      - 3000:3000
  dotnet-chatbot:
    image: mjrdockerregistry.azurecr.io/dotnet-chatbot-web:v1
    ports:
      - 8080:8080
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
